class Token():
    START_TOKEN = "__START__"
    END_TOKEN = "__END__"
    SEP_TOKEN = "__SEP__"
    DELIM_TOKEN = "__DELIM__"
    LINE_TOKEN = "__LINE__"
    TRIPLE_DOT_TOKEN = "__TRIPLE_DOT__"
    COMMA_TOKEN = "__COMMA__"
    CODE_TOKEN = "__CODE__"
    OR_TOKEN = "__OR__"
    QUESTION_TOKEN = "__QUESTION__"